name: Trivy Vulnerability Scanner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Trivy
        uses: aquasecurity/trivy-action@v0.0.1
        with:
          scan-type: 'filesystem'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: 'true'
          vuln-type: 'os,library'
          severity: 'HIGH,CRITICAL'

      - name: Run Trivy scan on OWASP Juice Shop
        run: trivy fs --scanners vuln,secret,misconfig https://github.com/juice-shop/juice-shop

      - name: Run Trivy scan on local instance
        run: trivy fs --scanners vuln,secret,misconfig /path/to/your/local/instance
