name: Trivy Vulnerability Scan on Juice Shop

on: [push, pull_request]

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Start Juice Shop Container
        run: |
          docker run -d --name juice-shop -p 3001:3000 bkimminich/juice-shop

      - name: Wait for Juice Shop to Start
        run: sleep 30  # Wait 30 seconds to ensure Juice Shop is fully running

      - name: Run Trivy Scan on Juice Shop
        run: |
          trivy --exit-code 0 --severity HIGH,CRITICAL http://localhost:3001 || true

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: Trivy Security Report
          path: trivy-security-report.txt
