name: Trivy Vulnerability Scan

on: [push, pull_request]

jobs:
  trivy-scan:
    name: Run Trivy Vulnerability Scanner
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Trivy
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://github.com/aquasecurity/trivy/releases/download/v0.24.2/trivy_0.24.2_Linux-64bit.deb
        sudo dpkg -i trivy_0.24.2_Linux-64bit.deb

    - name: Run Trivy on local files
      run: |
        trivy fs --severity HIGH,CRITICAL --output trivy-results.txt .

    - name: Upload Trivy results
      uses: actions/upload-artifact@v4
      with:
        name: trivy-results
        path: trivy-results.txt
